// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PharmacySystem.Models
{
    public partial class Invoice
    {
        public Invoice()
        {
            Item_Invoices = new HashSet<Item_Invoice>();
        }

        public int Invoice_No { get; set; }
        public DateTime Date { get; set; }
        public string CustName { get; set; }
        public double? TotalPrice { get; set; }
        public string Type { get; set; }
        public string Employee_Username { get; set; }

        public virtual Employee Employee_UsernameNavigation { get; set; }
        public virtual ICollection<Item_Invoice> Item_Invoices { get; set; }
    }
}